### ISSUE TITLE
Clipping modified inputs to [0, 255]

### ISSUE THREAD

**Issue by kenny-co** [tsborkar/Selective-feature-regeneration#1]
Might want to clip the resulting image when adding noise in the evaluation code:
`img_temp = np.clip(img_temp + adv_img, 0, 255)`

Not sure how this will change the reported results or affect the FRU results, but I don't think it matters so much for small norm values since it gets centered anyway.

**Comment by tsborkar** [comment]
You are correct. We didn't see any significant difference between the two. As a result, the [defense_example.py](https://github.com/tsborkar/Selective-feature-regeneration/blob/master/defense_example.py) does have clipping in each case. I did not add clipping in the evaluation code to ensure reproducibility of results from the paper, both for baseline and the defense.
